name: Branch Push

on:
  push:
    branches:
      - main
      - stage
      - dev

jobs:
  deploy-server:
    if: >
      contains(github.event.head_commit.message, '[ci]') && !contains(github.event.head_commit.message, '[vanilla]') &&
      (
        github.ref == 'refs/heads/main' ||
        github.ref == 'refs/heads/stage' ||
        github.ref == 'refs/heads/dev'
      )
    uses: ./.github/workflows/deploy-server.yaml
    secrets: inherit
  deploy-server-vanilla:
    if: >
      contains(github.event.head_commit.message, '[ci]') && contains(github.event.head_commit.message, '[vanilla]') &&
      (
        github.ref == 'refs/heads/main' ||
        github.ref == 'refs/heads/stage' ||
        github.ref == 'refs/heads/dev'
      )
    uses: ./.github/workflows/deploy-server-vanilla.yaml
    secrets: inherit
    
      


